# Generated by Django 5.1.3 on 2024-12-09 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasinoGame',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=255)),
                ('rules', models.TextField()),
                ('min_wager', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_wager', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_table_buyin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_table_buyin', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('ssn', models.CharField(max_length=9, unique=True)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('play_history_id', models.IntegerField(blank=True, null=True)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SignInHistory',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_logins', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Casino.user')),
            ],
        ),
        migrations.CreateModel(
            name='PlayHistory',
            fields=[
                ('play_id', models.AutoField(primary_key=True, serialize=False)),
                ('play_table_id', models.IntegerField()),
                ('session_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('play_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Casino.user')),
            ],
        ),
        migrations.CreateModel(
            name='Gameplay',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hand_wager', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hand_result', models.CharField(max_length=3)),
                ('casino_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Casino.casinogame')),
                ('game_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Casino.user')),
            ],
        ),
        migrations.CreateModel(
            name='AccountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('games_played', models.IntegerField()),
                ('total_wagered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Casino.user')),
            ],
        ),
    ]
